name: Update and Deploy

on:
  # Run this workflow whenever a new commit is pushed to main.
  push: {branches: [main]}
  # Run this workflow once per day, at 18:00 UTC
  schedule: [{cron: "0 18 * * *"}]
  # Run this workflow when triggered manually in GitHub’s UI.
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
      - name: Restore cached Fair Trading data
        id: cache-fairtrading-data-restore
        uses: actions/cache/restore@v4
        with:
          path: fair_trading_scraper/fair_trading_cache/**
          key: fairtrading-data-${{ hashFiles('fair_trading_scraper/fair_trading_cache/**') }}
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r fair_trading_scraper/requirements.txt
      - name: run FairTradingScraper
        run: python fair_trading_scraper/FairTradingScraper.py
      - name: Save Fair Trading data
        id: cache-fairtrading-data-save
        uses: actions/cache/save@v4
        with:
          path: fair_trading_scraper/fair_trading_cache/*
          key: fairtrading-data-${{ hashFiles('fair_trading_scraper/fair_trading_cache/**') }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist
      - run: ls dist/_file/data

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
      - name: Set up Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
