name: Update and Deploy

on:
  # Run this workflow whenever a new commit is pushed to main.
  push: {branches: [main]}
  # Run this workflow once per day, at 18:00 UTC
  schedule: [{cron: "0 18 * * *"}]
  # Run this workflow when triggered manually in GitHub’s UI.
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
      - name: Restore cached Fair Trading data
        id: cache-fairtrading-data-restore
        uses: actions/cache/restore@v4
        with:
          path: fair_trading_scraper/fair_trading_cache/*
          key: fairtrading-data
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r fair_trading_scraper/requirements.txt
      - name: run FairTradingScraper
        run: python fair_trading_scraper/FairTradingScraper.py
      - name: Save Primes
        id: cache-fairtrading-data-save
        uses: actions/cache/save@v4
        with:
          path: fair_trading_scraper/fair_trading_cache/*
          key: ${{ steps.cache-fairtrading-data-restore.outputs.cache-primary-key }}
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build
